[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true  # Enable FFI for deployment scripts to update .env file
unchecked_cheatcode_artifacts = true # we need this so test can run older solc verions (0.6.11 for DepositContract.sol)
no_match_coverage = "^test/|^script/"
no_match_path="test/invariant/*" #comment this line if wan to test invariants with -> forge test --mp "test/invariant/*"
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

[fuzz]
runs = 1024

[invariant]
runs = 512
depth = 64
fail_on_revert = false

[profile.strict.invariant]
runs = 512
depth = 64
fail_on_revert = true

#uncoment this for mock integration tests with -> forge test --mp "test/integration/*"
#[rpc_endpoints]
#mainnet = "${MAINNET_RPC_URL}"
