[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true  # Enable FFI for deployment scripts to update .env file
no_match_coverage = "^test/|^script/"
no_match_path="test/invariant/*"

[profile.coverage]
no_match_path = "test/invariant/*"

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fuzz]
runs = 1024

[invariant]
runs = 512
depth = 64
fail_on_revert = false

[profile.strict.invariant]
runs = 512
depth = 64
fail_on_revert = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
